# List of generated routes for better navigation:
# loevgaard_sylius_brand_admin_api_brand_index
# loevgaard_sylius_brand_admin_api_brand_create
# loevgaard_sylius_brand_admin_api_brand_update
# loevgaard_sylius_brand_admin_api_brand_show
# loevgaard_sylius_brand_admin_api_brand_delete
loevgaard_sylius_brand_admin_api_brand:
    resource: |
        identifier: code
        alias: loevgaard_sylius_brand.brand
        section: admin_api
        except: ['bulkDelete']
        grid: loevgaard_sylius_brand_admin_api_brand
        form: Loevgaard\SyliusBrandPlugin\Form\Type\BrandType
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api

loevgaard_sylius_brand_admin_api_brand_image:
    resource: "@LoevgaardSyliusBrandPlugin/Resources/config/routing/admin_api/brand_image.yml"
    prefix: /brands/{code}

loevgaard_sylius_brand_admin_api_brand_product_index:
    path: /brands/{code}/products/
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            serialization_version: $version
            section: admin_api
            serialization_groups: [Default]
            repository:
                method: createPaginatorForBrand
                arguments:
                    - expr:notFoundOnNull(service('loevgaard_sylius_brand.repository.brand').findOneByCode($code))
